//TryCatchFinally
try
	{

	}
catch (System.IO.IOException e)
	{

	}
finally
	{
           
	}